Feature/styles
oyova/wp-support pull request #4
Opened 2023-03-09 14:28 UTC by wnolfm

2023-03-10 13:08 UTC, ryanwhitman requested changes
Nolan, please be sure to run the fixer on this - https://github.com/oyova/wp-support/blob/feature/styles/CONTRIBUTING.md. Also, Rich can do the actual code review, but I assume these changes won't break any existing projects?

2023-03-10 14:03 UTC, wnolfm commented
@ryanwhitman No projects are using this style of block opener yet. So no, it won't break anything.

2023-03-10 22:37 UTC, wnolfm commented
Working on the class attribute. will reopen when complete.

2023-06-12 13:07 UTC, arjay-stanley commented on src/Acf/Blocks/Block.php
>  	public function get_element_class(): string {
rename to get_element_classes

2023-06-12 13:07 UTC, arjay-stanley commented on src/Acf/Blocks/Block.php
> +	public function get_wp_class(): array {
rename to get_wp_classes

2023-06-12 13:08 UTC, arjay-stanley requested changes
rename method `get_element_class` to `get_element_classes`
rename method `get_wp_class` to `get_wp_classes`

2023-06-12 14:22 UTC, merged